### ISSUE TITLE
Module not found on windows build

### ISSUE THREAD

**Issue by ManuelOverdijk** [Teamwork/node-auto-launch#12]
Hey, thanks for developing this module! 

It works fine, except one thing: 

I build my node-webkit application for windows and os x (currently developing on os x) with nw-builder. Running the builded package on os x works fine, except on windows the module 'auto-launch' can't be found. 

The module is installed via npm. Is there anything I need to configure specifically for windows?

**Comment by ManuelOverdijk** [comment]
As expected this wasn't a problem with this node module, but a problem with my nw-builder buildscript (forgot to explicitly package the auto-launch node_modules files within the executable). Strangly, it worked on OS X fine without the package files. 

Closed.

**Comment by orther** [comment]
@ManuelOverdijk I'm having the same issue. Could you elaborate on what you did to get this working?

**Comment by ManuelOverdijk** [comment]
@orther You should explicitly include the auto-launch module files within your nw-builder config, like so:

var nw = new NwBuilder({
    files: ['!www/bundle.js.map', 'www/**/**', 'node_modules/auto-launch/**/**'],
    version: 'v0.12.3',
    platforms: ['win32', 'osx64'],
    winIco: './www/img/app.ico'
});

**Comment by orther** [comment]
Thanks @ManuelOverdijk that worked.

I did have to change the pattern to use `**` _(globstar)_ to get it working with my project:
```js
var nw = new NwBuilder({
    files: ['!www/bundle.js.map', 'www//', 'node_modules/auto-launch/**/**'],
    version: 'v0.12.3',
    platforms: ['win32', 'osx64'],
    winIco: './www/img/app.ico'
});
```
