### ISSUE TITLE
Cannot disable.

### ISSUE THREAD

**Issue by makkesk8** [Teamwork/node-auto-launch#20]
Using windows 10, nw.js 0.12.3 running as administrator.

Looked at the source: 

```
disable: function(opts, cb) {
    return regKey.remove(opts.appName, cb);
  }
```

So its supposed to remove the key in regedit but it does not.

**Comment by MadLittleMods** [comment]
@makkesk8 This works fine for me on Windows 10 with a `nw.js@0.12.3` app. It shows up in the Task Manager Startup tab and everything.

**Comment by makkesk8** [comment]
@MadLittleMods Yes, it shows up as enabled in task manager but doing the .disable wont show it as disabled and restarting will still start it.

**Comment by MadLittleMods** [comment]
@makkesk8 I just did some thorough testing and it works fine for me as a rough add/remove from the startup list. `enable` will add it to the startup list and will start the app on launch. `disable` will remove it from the startup list and nothing happens on launch.

Changing the status as `Disabled` is a separate issue I made here: https://github.com/Teamwork/node-auto-launch/issues/22

It does sound like it isn't working properly for you though.

**Comment by makkesk8** [comment]
@MadLittleMods Exactly, your scenario just doesn't happen for me... It's still in the startup list and will remain there until i delete it manually.

**Comment by 4ver** [comment]
Is the callback receiving an error after you call disable?

**Comment by makkesk8** [comment]
@4ver No sir.

**Comment by 4ver** [comment]
I'm not sure if it will help considering how small our api is but can you provide a sample of what you are doing?

Thanks for getting back.
