### ISSUE TITLE
Electron Application Not Opening On Startup - MacOS

### ISSUE THREAD

**Issue by aksharj** [Teamwork/node-auto-launch#23]
Hello There,

I am trying to open a simple electron application on startup. Below is my code, i think i am doing something wrong, can you please help. Please pardon me if i have missed something. Thanks.

'use strict';

var AutoLaunch = require('auto-launch');

var appLauncher = new AutoLaunch({
    name: 'My NW.js or Electron app'
});

appLauncher.isEnabled(function(enabled){
    if(enabled) return;

    appLauncher.enable(function(err){

    });

});

// Module to control application life.
const app = electron.app;
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow;

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow;

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1620, height: 740});

  // and load the index.html of the app.
  mainWindow.loadURL('http://orcatv.net/pace/nyc720.php');

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow();
  }
});

**Comment by 4ver** [comment]
Your usage is perfect. Have you checked if there is an error being passed to the `enable` callback? If there is send it on.

Thanks,
Donal.
