### ISSUE TITLE
Can't get correct isEnabled() result in menu click function (only on mac)

### ISSUE THREAD

**Issue by phaibin** [Teamwork/node-auto-launch#25]
I can get corrent isEnabled() result for the first time. But when runing isEnabled() in a menu click function it always returns "false". And when I print loginItems gotten from apple script, it will be "undefined". I think the root cause is from "applescript" package.

**Comment by maxnowack** [comment]
same here. Any workarounds?

**Comment by adam-lynch** [comment]
Can someone confirm if #38 fixes this?
