### ISSUE TITLE
Windows registry key pointing to an older version of an electron-based app after an upgrade using Squirrel

### ISSUE THREAD

**Issue by djpereira** [Teamwork/node-auto-launch#29]
The install location of the .exe for Windows changes as you update your app when you use Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/install-process.md#install-location).

When you call the `enable` command, auto-launch creates a registry key using the path to the current version, but this does not get updated as you deploy newer versions of your app thru Squirrel and electron's auto-update.

A possible workaround is to listen to the `--squirrel-updated` event and call the `enable` command again, so the registry key gets recreated.

I am wondering if I am missing something or if there is a better workaround.

**Comment by MarshallOfSound** [comment]
@djpereira @adam-lynch 

Squirrel has a springboard style exe launcher using Update.exe

`update.exe --processStart "name of exe.exe"`

I'll PR this in

**Comment by adam-lynch** [comment]
Thanks for pointing this out by the way 👍
