### ISSUE TITLE
How to make it compatible with sandboxed Electron app for Mac App Store? 

### ISSUE THREAD

**Issue by miloszfalinski** [Teamwork/node-auto-launch#30]
Anyone has any experience as to how to make auto-launch work on a Mac App Store Electron build? 

All system-level functionality is locked by default, so it will probably need to be enabled in the entitlements files used to sign the build. I've tried adding temporary exceptions like below, but it doesn't seem to work. 
```
<key>com.apple.security.temporary-exception.apple-events</key>
<array>
    <string>com.apple.systemevents</string>
</array>
```

**Comment by adam-lynch** [comment]
Unfortunately, we haven't experience with this.

**Comment by adam-lynch** [comment]
OK I've learned a good bit about this today. I've rewritten the [README](https://github.com/Teamwork/node-auto-launch#how-does-it-work) with explanations on how it works (plus how the new alternative method for Mac works) and #43 explains why we can't support the Mac App Store. It's really tricky. I'm sorry.
