### ISSUE TITLE
Electron app not hidden on startup

### ISSUE THREAD

**Issue by sam-jay** [Teamwork/node-auto-launch#31]
I've tried setting isHidden to both true and false but neither works.

I'm guessing that calling the ```show()``` method on the main electron window is what's causing this behavior. How do I check that the app has launched at startup to avoid showing the main window?

**Comment by adam-lynch** [comment]
Could you retry with the latest version? #26 and #27 were merged & released.

**Comment by Razzeee** [comment]
Doesn't work for me with windows either. Seems like the --hidden is not understood by the exe created by electron-packager?

**Comment by wangxiexe** [comment]
does not work for me on windows 10 either.

**Comment by adam-lynch** [comment]
#39 is a potential fix... but can you all confirm that you're using Squirrel (autoUpdater)?

**Comment by Razzeee** [comment]
Well Iam obviously :)
Let's wait for the others

**Comment by wangxiexe** [comment]
I am also using Squirrel, previously it worked well for me. 

I updated to v4.0 and noticed previously in the windows registry the value is 

"C:\Users\wangxi\AppData\Local\MiCloudPC\app-0.0.252\MiCloudPC.exe" --hidden

but now 

"C:\Users\wangxi\AppData\Local\MiCloudPC\update.exe" --processStart "MiCloudPC.exe" --hidden

and then seems hidden is not passed in....

**Comment by SavageCore** [comment]
Not working for me with electron-builder, any hints?
