### ISSUE TITLE
Asar not packing auto launch

### ISSUE THREAD

**Issue by sandeep2** [Teamwork/node-auto-launch#33]
I am currently using electron-packager to get convert my electron app to executable. It uses asar to pack all the node modules but auto-launch module is not packed by asar. When I unpack the asar and then put auto-launch into the node-modules and then packing it works fine. Does anyone else have the same problem ?

**Comment by adam-lynch** [comment]
I'm not 100% sure but maybe this module breaks some of [limitations/exceptions of asar](http://electron.atom.io/docs/tutorial/application-packaging/#limitations-on-node-api). Maybe you'll need to  use the [`--unpack` option](http://electron.atom.io/docs/tutorial/application-packaging/#adding-unpacked-files-in-asar-archive) for this module?
