### ISSUE TITLE
not work with lastest electron

### ISSUE THREAD

**Issue by wangxiexe** [Teamwork/node-auto-launch#37]
1) I found there is still es6-promise reference even you mentioned in lastest version it will be remove

Promise = require('es6-promise').Promise;

in dist/index.js

2) then I installed es6-promise and it does not have any error now, but it does not make my app lanuch on windows startup by doing

        appLauncher.enable()

My electron is v1.3.3

3) what I want is auto launch as minimised on tray, hope this feature can be provied. 

Thanks.

**Comment by joeferraro** [comment]
Was the source re-compiled before pushing the update to npm? I see that `es6-promise` was removed from `/src`, but when I `npm install` references to `es6-promise` still remain in /dist

**Comment by smithalan92** [comment]
Hey @wangxiexe and @joeferraro , your both right, 3.0.0 was never rebuilt before publishing. We've published those changes now as 4.0.0 just so anyone using 3.0.0 doesnt get the update in case they're still using the es6-promise module. @wangxiexe I'm going to close this issue. Feel free to open another issue if v4 doesn't solve your problems.
