### ISSUE TITLE
Doesn't auto start but entry is in regedit

### ISSUE THREAD

**Issue by alexcroox** [Teamwork/node-auto-launch#4]
So I've run the example and I now have an entry in this part of regedit https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchWindows.coffee#L5

but it doesn't start on login for some reason. Is there anyway to debug this? The .exe is set to run as administrator, could this be blocking it's auto start?

**Comment by alexcroox** [comment]
It's also listed in task manager > startup tab. It auto starts on a friends computer but he's running Vista not Windows 8. I'm convinced it's because it's set to the run as administrator. Anyway I can debug it to provide you with more info?

**Comment by adam-lynch** [comment]
@4ver any ideas?

**Comment by alexcroox** [comment]
This was the fix for me, not ideal...

http://superuser.com/questions/609317/how-do-i-make-every-program-run-as-an-admin/609356#609356
