### ISSUE TITLE
Highlighting is broken on github

### ISSUE THREAD

**Issue by fritx** [Teamwork/node-auto-launch#40]
Looks like it is caused by `### Public ###`

![image](https://cloud.githubusercontent.com/assets/6647633/18117952/81c0a424-6f84-11e6-8909-24174e3463b8.png)

**Comment by adam-lynch** [comment]
Yeah, not sure why though 😕

**Comment by adam-lynch** [comment]
Fixed.

**Comment by fritx** [comment]
Still not fixed @adam-lynch

**Comment by adam-lynch** [comment]
Hmm, just seems to be `index.coffee`. Not sure what we can do. It's not a bug with this module anyway I guess

**Comment by fritx** [comment]
I just guess if you remove things like `###`, it could be fixed.
It's not a bug of this module indeed, but it does break guys viewing code on Github, doesn't it?
