### ISSUE TITLE
Uncaught Exception: Cannot find module 'applescript'

### ISSUE THREAD

**Issue by sidneys** [Teamwork/node-auto-launch#44]
- The target platform: **macOS 10.11**
- Node version: **5.6.0**
- auto-launch version: **5.0.0**
- The options you're passing to auto-launch: **name (packageJson.name)**
- Are you using NW.js or Electron?  **Electron 1.4.0 (main process)**
- Can you reproduce this with a simple Hello World example app? **Yes**
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem? **electron-sample-app**

---

- After building the app with electron-packager, launching the generated .app results in the error:
  ![screenshot](http://i.imgur.com/wTutADp.png)

- Manually adding the `applescript` dependency to the project mitigates the problem.

**Comment by adam-lynch** [comment]
Sorry about that! 5.0.1 published. Thanks for reporting.
