### ISSUE TITLE
Autolaunch in linux (ubuntu) launches electron executable - not the electron app. 

### ISSUE THREAD

**Issue by amalbose** [Teamwork/node-auto-launch#48]
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Ubuntu
- Node version (run `node -v`): v7.0.0
- auto-launch version: 5.0.1
- The options you're passing to auto-launch: 
 
var axareminderLauncher = new AutoLaunch({
    name: 'AxaReminder',
    isHidden: true,
});
- Are you using NW.js or Electron? Electron 
  - If so, which version? 1.4.0
  - If you're using Electron, are you using auto-launch from the main process or a renderer process? Main process

---

The autostart file created is for electron executable and not the electron app.
This is the options given.
var axareminderLauncher = new AutoLaunch({
    name: 'AxaReminder',
    isHidden: true,
});

Even though the name is given, this is the file created.
Type=Application
Version=1.0
Name=electron
Comment=electronstartup script
Exec=/usr/lib/node_modules/electron/dist/electron --hidden
StartupNotify=false

Issues:
1. Name is wrong
2. exec is for electron app not the actual application.

**Comment by fretman92** [comment]
First, thank you for your work, highly appreciated here in Lyon (France) ;)

I think I have the same problem on macOS,
At clean startup, with packaged version of my Electron app, the Terminal opens and runs `~/Downloads/MyApp.app/Contents/MacOS/Myapp ; exit ;"

**Comment by ajantiss** [comment]
I currently face the same issue, did you find an workaround / fix before checking out and spot it why ?

**Comment by ajantiss** [comment]
Ok, I answer to myself and @amalbose  in case it could still help...

Basically you should have done as me, i.e. defining something like
`  launch = new AutoLaunch({
    name: app.getName()
  });`

For Electron as quoted in doc, path, is automatically filled with 

> process.execPath

This means that it cannot work in development, as it will always map to your electron executable. 
The only way to make it work is simply to build a deb package and install it, you'll see that works perfectly fine once it is bundled in a packaged application.

**Comment by makalatarun** [comment]
Hi, can you please explain how exactly did debian package worked. I made a debian package of my app but it is not working.

**Comment by adam-lynch** [comment]
I think @ajantiss is right. You can't use this in development. When I'm testing, I run `npm run pack` (see [electron-builder](https://github.com/electron-userland/electron-builder)), then open the generated app. P.S. this module is handy for checking if your app is currently running in development: https://github.com/sindresorhus/electron-is-dev.
