### ISSUE TITLE
Issue creating auto-launch for Mac + nwjs

### ISSUE THREAD

**Issue by AbrahamNevadoZazo** [Teamwork/node-auto-launch#60]
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Mac 10.12.4
- Node version (run `node -v`):  v6.10.0
- auto-launch version: 5.0.1
- The options you're passing to auto-launch: just name
- Are you using NW.js or Electron? Yes
  - If so, which version? NWjs  58.0.3029.110 
  - If you're using Electron, are you using auto-launch from the main process or a renderer process?
- Can you reproduce this with a simple Hello World example app?
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem?

---

Once I create auto-launch for my application it fails with the next error:

[0608/100331.289731:FATAL:chrome_main_delegate.cc(783)] Check failed: command_line.HasSwitch(switches::kProcessType) && !process_type.empty(). Helper application requires --type.
0   nwjs Framework                      0x000000010c382eb3 _ZN2v88UnlockerD1Ev + 15202595
1   nwjs Framework                      0x000000010c39c037 _ZN2v88UnlockerD1Ev + 15305383
2   nwjs Framework                      0x000000010aaa7683 ChromeMain + 3539
3   nwjs Framework                      0x000000010aaa7794 ChromeMain + 3812
4   nwjs Framework                      0x000000010bfb8d62 _ZN2v88UnlockerD1Ev + 11229138
5   nwjs Framework                      0x000000010bfb83be _ZN2v88UnlockerD1Ev + 11226670
6   nwjs Framework                      0x000000010aaa68fb ChromeMain + 75
7   nwjs Helper                         0x000000010aa6ddca main + 522
8   libdyld.dylib                       0x00007fffb2cdf235 start + 1

And the process exists. 

The command that is being invoked with AppleScript or with Launch agent is:
"Alertsite Desktop Proxy.app/Contents/Versions/57.0.2987.98/nwjs Helper.app/Contents/MacOS/nwjs Helper"

If however the command were:

"Alertsite Desktop Proxy.app/Contents/MacOS/nwjs" 

It would work like a charm.  Am I doing something wrong ? 

Thanks a lot in advance.

**Comment by adam-lynch** [comment]
This should be fixed in `5.0.2`. Let us know if not.
