### ISSUE TITLE
[question] What versions of Windows does this support?

### ISSUE THREAD

**Issue by fritx** [Teamwork/node-auto-launch#7]
```coffee
regKey = new Winreg
  hive: Winreg.HKCU
  key:  '\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'
```

**Comment by adam-lynch** [comment]
I think we've had users on XP and newer. Correct me if I'm wrong @4ver

**Comment by fritx** [comment]
Thanks. Unfortuately sometimes I'm not allowed to access winreg, so it seems I could only do it via Startup Menu.

**Comment by adam-lynch** [comment]
Not sure if this is what you mean but we've had cases where the user's environement variables are messed up and Windows doesn't recognize the `reg` command (unless you're literally in the `System32` directory). In that case, we catch the specific error and show the user a fatal error screen linking to http://support.teamwork.com/chat/my-account/how-can-i-fix-my-environment-variables

**Comment by fritx** [comment]
Thanks! Bookmarked, interesting case!
But my case is different: some certain machines of our users are not allowed to access the reg, just due to some security reasons. :cry:

**Comment by adam-lynch** [comment]
Hmm. Is this some kind of Windows' setting? I wonder how likely it is one of our users' machines would be like this and cause issues.

**Comment by fritx** [comment]
I'm afraid not ;) that is configured explictly in our company. in some important departments like R&D, apps in their machines are only allowed to access space excluding C: & reg. :/

**Comment by adam-lynch** [comment]
Hmm ok.
