### ISSUE TITLE
Mac auto launch through LaunchAgent does not work

### ISSUE THREAD

**Issue by wmin0** [Teamwork/node-auto-launch#71]
- Platform: Mac
- Node version: 8.5.0
- auto-launch version: 5.0.3
- Electron: 1.6.8 main process

---

According to #34 , if the given path is the path of inner binary, it will be replace to app directory itself.
It may should graceful information in Login Item Preferences.
However, it breaks with LaunchAgent, because LaunchAgent needs inner binary path.

**Comment by adam-lynch** [comment]
Hey, thanks for reporting this but I can't reproduce it. See the screenshot below:
 
<img width="743" alt="screen shot 2017-12-02 at 13 10 42" src="https://user-images.githubusercontent.com/1427241/33515973-4afb1838-d762-11e7-9e05-dd0c869b7a4f.png">

If it's still a problem for you, could you provide an example app which reproduces the problem?

**Comment by wmin0** [comment]
@adam-lynch I report the bug about LaunchAgent not about LoginItems. I think you should set useLaunchAgent: true.

![image](https://user-images.githubusercontent.com/3232626/33516161-cefd1dd4-d7a8-11e7-95e6-2719ad24478f.png)

**Comment by adam-lynch** [comment]
Ah! You're right. 

I can reproduce now. I'll be busy today but I might get to it tonight or tomorrow.

cc @JBLatenight @lucasbento.

**Comment by adam-lynch** [comment]
I just published 5.0.4. Let me know if there are any problems. Thanks again for reporting.

**Comment by wmin0** [comment]
@adam-lynch Thanks your work 😃

**Comment by mavrick** [comment]
Could we get ``npm`` updated with the latest version as well please? 😄

**Comment by mavrick** [comment]
Looks like there is a build issue @adam-lynch https://travis-ci.org/Teamwork/node-auto-launch

**Comment by adam-lynch** [comment]
Ugh I don't know what happened. I tried to publish just now and it said I can't publish over an existing version. So I published 5.0.5. (Build error is unrelated, that's another branch)
