### ISSUE TITLE
executable doesn't start because of spaces in path

### ISSUE THREAD

**Issue by seasick** [Teamwork/node-auto-launch#73]
- The target platform(s) the problem occurs on *Linux*
- Node version (run `node -v`): *6.11.5*
- auto-launch version: *5.0.3*
- The options you're passing to auto-launch: `{"name": "my-desktop"}`
- Are you using NW.js or Electron? *Electron*
  - If so, which version? *1.7.9*
  - If you're using Electron, are you using auto-launch from the main process or a renderer process? *main*

The generated `.desktop` file in `~/.config/autostart` looks like the following
```
[Desktop Entry]
Type=Application
Version=1.0
Name=my-desktop
Comment=my-desktopstartup script
Exec=/opt/My Desktop/my-desktop
StartupNotify=false
Terminal=false
```

It would work with the space being escaped (`Exec=/opt/My\ Desktop/my-desktop`), or the complete path put within quotes (`Exec="/opt/My Desktop/my-desktop"`). At least that is what I've tested on my system (Ubuntu 16.04) and worked. It did work on OSX and Windows though.

**Comment by adam-lynch** [comment]
Thanks. I'd love if you could submit a pull-request to fix this 😄

**Comment by adam-lynch** [comment]
Actually, can you confirm https://github.com/Teamwork/node-auto-launch/pull/57 would also fix it?

**Comment by seasick** [comment]
Yes, I believe this would fix it
