### ISSUE TITLE
Linux desktop entry file is named based on `path`, not `name`

### ISSUE THREAD

**Issue by artemv** [Teamwork/node-auto-launch#90]
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows): Linux, Ubuntu 18.04.1 LTS
- Node version (run `node -v`):  10.11.0
- auto-launch version: 5.0.5
- The options you're passing to auto-launch:  {name: 'My Desktop App', path: process.env.APPIMAGE}
- Are you using NW.js or Electron? Electron
  - If so, which version? 2.0.7
  - If you're using Electron, are you using auto-launch from the main process or a renderer process? main
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem? yes
---

I'm packaging my Electron app as AppImage for Linux, and pass the `{path: process.env.APPIMAGE}` option to make it work, which becomes e.g. `{path: "/home/artem/Downloads/my-desktop-app-0.17.36-x86_64.AppImage"}`. The desktop entry created by auto-launch has a `my-desktop-app-0.17.36-x86_64.AppImage.desktop` filename in this case. This works fine but then when new version of the app is published another desktop entry file is created, `my-desktop-app-0.17.37-x86_64.AppImage.desktop`, and so on, polluting the `autostart` dir. 

Let's base the desktop entry filename on the `name` option instead, in this case it would be `My Desktop App.AppImage.dektop`. Also, let's use the passed `name` option for the `name` property of dektop entry file - currently it uses filename part of `path` option instead.

**Comment by adam-lynch** [comment]
Please see that we're looking for contributors / maintainers: #64.

I'm happy to give access to people who are willing to help improve things, merge pull-requests, close issues, etc.

**Comment by kroko** [comment]
@adam-lynch any chances you give access to @artemv so this can be merged (if he even is interested after all this time)? 😄 this package in combination with AppImage in combination with auto updates produces mess on end users system.

> We've neglected this project a little bit. Apologies.

> We're going to fix this. We're going to allocate dev time each month or something like that to keep a better eye on the project.

The issues list as well as PRs grow, imho this has come to point, where either this needs to be resolved or some `node-auto-launch-next` has to be created -> this repo is in coffee (I am aware of https://github.com/Teamwork/node-auto-launch/issues/66) one just cannot _npm install_ some github fork from PRs, gulping is needed, meanwhile you hold the keys to npm package.

Thank you for the great package nonetheless!
