### ISSUE TITLE
Check if app is hidden at launch at login or manually by the user

### ISSUE THREAD

**Issue by ilDon** [Teamwork/node-auto-launch#93]
I have integrated auto-launch in my Electron app. I would like not to open the main window of the app when the app is auto-launched at startup. Is there a way to determine if the app was launched by the user, or if it has been auto-launched at system startup?

**Comment by Connum** [comment]
Here's a workaround I'm using: After initialising the AutoLauncher, overwrite the appPath with something like this:

```js
this.AutoLauncher.opts.appPath += '" --autostart "'
```

Notice the double quotes inside the single quotes. auto-launch automatically encloses the appPath with double quotes when writing to the registry, so what this does is closing the double quotes behind the path, adding an `--autostart` command line argument (or whatever you want to name it) and then opening double quotes again, so you end up with this in the registry:

    "X:\Your\app\path\app.exe" --autostart ""

You end up having a set of double quotes as an additional command line argument as well, but that shouldn't hurt. Now you can check in your app if the argument is set and react to it accordingly.

I only tested this under Windows and it's a bit hack-ish, but as long as adding command line arguments is not natively supported by this package, it works.

**Comment by adam-lynch** [comment]
Please see that we're looking for contributors / maintainers: #64.

I'm happy to give access to people who are willing to help improve things, merge pull-requests, close issues, etc.

**Comment by Noitidart** [comment]
@Connum can you share more code please. I don't understand what you mean by after initializing the autolauncher.

**Comment by Connum** [comment]
> 
> 
> @Connum can you share more code please. I don't understand what you mean by after initializing the autolauncher.

```
var AutoLauncher = new AutoLaunch({
    name: 'MyAppName'
});

AutoLauncher.opts.appPath += '" --autostart "';

AutoLauncher.enable();
```

**Comment by Noitidart** [comment]
Thank you! I will test on mac and let you know how it goes.

**Comment by Noitidart** [comment]
There seems to be an option to `enable` called `isHiddenOnLaunch`:

* Windows - https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchWindows.coffee#L20
* macOS - https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchLinux.coffee#L13
* Linux - https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchMac.coffee#L17

So if we set this to true we can detect if it was auto-launched by looking for the "hidden" argument. I haven't tried this yet, just peeked at the source and am theorizing. I haven't visited this app in over a month, hope to try stuff out soon.

**Comment by newCodeRunner** [comment]
@Noitidart , @Connum , did you find a solution for this? I am on Mac, and I can't use the solution proposed by @Connum , also the --hidden argument is not present in Electron's main entry file (process.argv)

**Comment by Noitidart** [comment]
I didn't find a solution. :(

**Comment by Connum** [comment]
A year and a half later and not having worked much with Electon since, all I can say is that I had it working with my workaround. But I can't say if this still works with more recent versions of Electon.

**Comment by newCodeRunner** [comment]
@Noitidart , @Connum thank you for your quick reply.

Well for anyone looking for a solution, here is what I did.
Electron-v10.1.5
OS- Mac

I used the Electron's built in
`app.setLoginItemSettings({ openAtLogin: true, args: ['--startup'])`
and
`app.getLoginItemSettings().wasOpenedAtLogin // for mac only`
to check if the app was opened at startup, and then used my Electron Main process entry file to open main window or use NodeJs child-proc to execute another binary. Hacky, but this is all I got after 2 days searching.

For windows users, they can make use of  NodeJS built-in (process.argv) to check if '--startup' is present at Electron Main process entry file, and then do the same processes accordingly.

**Comment by Noitidart** [comment]
Thanks for sharing your learnings!

**Comment by stenya** [comment]
To summarize the comment from @newCodeRunner, this snipped works on Windows\Linux\macOS (Electron v12.0.0).
Not even necessary to call `app.setLoginItemSettings(...)` 

```
import { app } from "electron";

let launcherOptions = { name: "AppName", isHidden: true }; // isHidden is in use by Windows and Linux implementation (see function: WasOpenedAtLogin())
let autoLauncher = new AutoLaunch(launcherOptions);

...

export function WasOpenedAtLogin() {
  try {
    if (Platform() === PlatformEnum.macOS) {
      let loginSettings = app.getLoginItemSettings();
      return loginSettings.wasOpenedAtLogin;
    }
    return app.commandLine.hasSwitch("hidden");
  } catch {
    return false;
  }
}

export async function AutoLaunchSet(isEnabled) {
  if (isEnabled) await autoLauncher.enable();
  else await autoLauncher.disable();
}
```

**Comment by Oxalin** [comment]
This is the way to go, at least for now.

Auto-launch could have dealt with extra arguments uniformly without this specific use case. Since we handle this one specifically  ("hidden"), maybe we could explore what could be improved in auto-launch to make things even easier.

I'm opening an issue to track some ideas: https://github.com/Teamwork/node-auto-launch/issues/128
